FROM postgres:16

WORKDIR /app

# Add setup script & exec permission
ADD dbSetup.sh /app
RUN chmod +x dbSetup.sh

# Add SQL setup script & data file
ADD ./sql/schema/cpu_usage.sql /app
ADD ./data/cpu_usage.csv /app

# Run!
CMD ["bash", "/app/dbSetup.sh"]
