FROM postgres:16

WORKDIR /app

# Postgres username & password
ENV DB_USER=
ENV DB_PASS=
ENV DB_URL=
# TODO: Pull from .env file
ENV DB_DATABASE=tsdb
ENV DB_OPTIONS=sslmode=require

# Add setup script & exec permission
ADD dbSetup.sh /app
RUN chmod +x dbSetup.sh

# Add SQL setup script & data file
ADD cpu_usage.sql /app
ADD cpu_usage.csv /app

# Run!
CMD ["bash", "/app/dbSetup.sh"]
